# Alembic Configuration
# https://alembic.sqlalchemy.org/

[alembic]
# path to migration scripts
script_location = migrations

# template_location =

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to os.environ['TZ'] set before importing datetime module.
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in an migration file name.
# set to 0 to disable, omitting returns
# the legacy behavior of due date/time
# len_suffix =
max_length = 40

# Logging configuration
# Logging can be off, 'error', 'info', 'warning' (default) or 'debug' (most verbose)
# - When this value is changed from its current setting, try running
#   the alembic command with `--autogenerate` to detect
#   changes to the models, as only changed files may contain new enough
#   features for the revision scripts to detect what's changed.
log_level = warning

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
